# tools/report_tools.py
from fpdf import FPDF
from fpdf.enums import XPos, YPos
from datetime import datetime
import os
from typing import Dict, Any, List, Optional
import logging

from utils.helpers import format_currency, format_percentage, format_large_number

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class PDFReport(FPDF):
    """Custom PDF class for stock reports"""
    
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        
    def header(self):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(0, 51, 102)  # Dark blue
        # Fixed: Replaced ln=1 with new_x=XPos.LMARGIN, new_y=YPos.NEXT
        self.cell(0, 10, 'Finlyze - AI-Powered Stock Analysis Report', 
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
        self.ln(5)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)  # Gray
        # Fixed: Replaced ln=0 with new_x=XPos.RIGHT, new_y=YPos.TOP
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} | Generated by Finlyze AI', 
                  new_x=XPos.RIGHT, new_y=YPos.TOP, align='C')
    
    def section_title(self, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(0, 51, 102)  # Dark blue
        self.set_fill_color(240, 240, 240)  # Light gray
        # Fixed: Replaced ln=1 with new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill parameter
        self.cell(0, 10, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='L', fill=True)
        self.ln(4)
    
    def subsection_title(self, title):
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(0, 0, 0)  # Black
        # Fixed: Replaced ln=1 with new_x=XPos.LMARGIN, new_y=YPos.NEXT
        self.cell(0, 6, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='L')
        self.ln(2)
    
    def section_body(self, text):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(0, 0, 0)  # Black
        self.multi_cell(0, 5, text)
        self.ln(5)
    
    def add_chart(self, chart_path, caption=""):
        if os.path.exists(chart_path):
            try:
                # Calculate dimensions to fit page
                self.image(chart_path, x=10, w=190)
                if caption:
                    self.set_font('Helvetica', 'I', 9)
                    self.set_text_color(100, 100, 100)
                    # Fixed: Replaced ln=1 with new_x=XPos.LMARGIN, new_y=YPos.NEXT
                    self.cell(0, 5, caption, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
                self.ln(5)
            except Exception as e:
                logger.error(f"Error adding chart: {str(e)}")
    
    def add_key_value(self, key, value, indent=0):
        """Add a key-value pair in a formatted way"""
        self.set_font('Helvetica', 'B', 10)
        # First cell: key (no line break)
        self.cell(40 + indent, 6, key + ':', new_x=XPos.RIGHT, new_y=YPos.TOP, align='L')
        self.set_font('Helvetica', '', 10)
        # Second cell: value (with line break)
        self.cell(0, 6, str(value), new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='L')
    
    def add_table(self, headers, data, col_widths=None):
        """Add a simple table"""
        if not col_widths:
            col_widths = [self.w / len(headers)] * len(headers)
        
        # Headers
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(200, 200, 200)
        for i, header in enumerate(headers):
            self.cell(col_widths[i], 7, header, border=1, new_x=XPos.RIGHT, new_y=YPos.TOP, align='C', fill=True)
        self.ln()
        
        # Data rows
        self.set_font('Helvetica', '', 9)
        for row in data:
            for i, cell in enumerate(row):
                self.cell(col_widths[i], 6, str(cell), border=1, new_x=XPos.RIGHT, new_y=YPos.TOP, align='L')
            self.ln()

def generate_pdf_report(
    ticker: str,
    company_data: Dict[str, Any],
    news_data: Dict[str, Any],
    analysis_summary: str,
    recommendation: str,
    chart_paths: List[str] = None
) -> str:
    """
    Generate comprehensive PDF report
    """
    try:
        pdf = PDFReport()
        pdf.add_page()
        pdf.alias_nb_pages()  # For page numbers
        
        # Title
        pdf.set_font('Helvetica', 'B', 20)
        pdf.set_text_color(0, 51, 102)
        pdf.cell(0, 15, f'{ticker} Analysis Report', new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, f'Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M")}', 
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
        pdf.ln(10)
        
        # Company Overview
        pdf.section_title('1. Company Overview')
        
        company_name = company_data.get('company_name', ticker)
        pdf.set_font('Helvetica', 'B', 12)
        pdf.cell(0, 8, company_name, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        # Key stats in a table
        pdf.subsection_title('Key Statistics')
        
        stats_data = [
            ['Current Price', format_currency(company_data.get('current_price'))],
            ['Market Cap', format_currency(company_data.get('market_cap'))],
            ['P/E Ratio', f"{company_data.get('pe_ratio', 'N/A'):.2f}" if company_data.get('pe_ratio') else 'N/A'],
            ['EPS', f"${company_data.get('eps', 0):.2f}" if company_data.get('eps') else 'N/A'],
            ['52W High', format_currency(company_data.get('high_52w'))],
            ['52W Low', format_currency(company_data.get('low_52w'))],
            ['Volume', format_large_number(company_data.get('volume', 0))],
            ['Avg Volume', format_large_number(company_data.get('avg_volume', 0))],
            ['Dividend Yield', format_percentage(company_data.get('dividend_yield'))],
            ['Beta', f"{company_data.get('beta', 'N/A'):.2f}" if company_data.get('beta') else 'N/A']
        ]
        
        for key, value in stats_data:
            pdf.add_key_value(key, value)
        
        pdf.ln(5)
        
        # Charts
        if chart_paths:
            pdf.section_title('2. Visual Analysis')
            for i, chart_path in enumerate(chart_paths):
                if i == 0:
                    pdf.add_chart(chart_path, "Price Chart with Moving Averages")
                elif i == 1:
                    pdf.add_chart(chart_path, "Trading Volume Analysis")
                else:
                    pdf.add_chart(chart_path, "")
        
        # News & Sentiment
        pdf.section_title('3. News & Market Sentiment')
        
        if news_data and news_data.get('news'):
            sentiment = news_data.get('sentiment', {})
            overall = sentiment.get('overall', 'neutral').upper()
            
            # Sentiment summary
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(0, 6, f"Overall Sentiment: {overall}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font('Helvetica', '', 9)
            pdf.cell(0, 5, f"Positive: {sentiment.get('positive_count', 0)} | Negative: {sentiment.get('negative_count', 0)} | Neutral: {sentiment.get('neutral_count', 0)}", 
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.ln(3)
            
            # Top news headlines
            pdf.subsection_title('Recent Headlines:')
            for i, article in enumerate(news_data['news'][:5], 1):
                pdf.set_font('Helvetica', 'B', 9)
                pdf.multi_cell(0, 4, f"{i}. {article.get('title', 'No title')}")
                pdf.set_font('Helvetica', '', 8)
                pdf.cell(0, 4, f"   Source: {article.get('source', 'Unknown')} | {article.get('date', '')}", 
                         new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.ln(2)
        else:
            pdf.section_body("No recent news found for this ticker.")
        
        # Analysis Summary
        pdf.section_title('4. Analysis Summary')
        pdf.section_body(analysis_summary)
        
        # Recommendation
        pdf.section_title('5. Recommendation')
        
        # Color code recommendation
        if 'BUY' in recommendation.upper():
            pdf.set_text_color(0, 128, 0)  # Green
        elif 'SELL' in recommendation.upper():
            pdf.set_text_color(255, 0, 0)  # Red
        else:
            pdf.set_text_color(255, 140, 0)  # Orange
        
        pdf.set_font('Helvetica', 'B', 14)
        pdf.cell(0, 10, recommendation, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        # Disclaimer
        pdf.set_text_color(100, 100, 100)
        pdf.set_font('Helvetica', 'I', 8)
        pdf.ln(10)
        pdf.multi_cell(0, 4, "DISCLAIMER: This report is generated by an AI system for informational purposes only. Not financial advice. Always do your own research before making investment decisions.")
        
        # Save PDF
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        pdf_path = f"output/{ticker}_report_{timestamp}.pdf"
        
        # Create output directory if it doesn't exist
        os.makedirs("output", exist_ok=True)
        
        pdf.output(pdf_path)
        
        # Verify file was created
        if os.path.exists(pdf_path):
            file_size = os.path.getsize(pdf_path)
            logger.info(f"✅ PDF report generated: {pdf_path} ({file_size} bytes)")
        else:
            logger.error(f"❌ PDF file not found after generation: {pdf_path}")
            
        return pdf_path
        
    except Exception as e:
        logger.error(f"Error generating PDF: {str(e)}")
        import traceback
        logger.error(traceback.format_exc())
        return None